name: Deploy Prod

on:
  push:
    branches:
      - main
    paths:
      - "config/**"
      - "src/**"
      - ".github/workflows/*.yml"

env:
  NODE_VERSION: "22.19.0"

permissions:
  contents: read
  deployments: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Set Vercel Environment Variables
        run: |
          vercel env rm DEBUG production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm FASTAPI_HOST production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm FASTAPI_PORT production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm FASTAPI_TITLE production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm FASTAPI_VERSION production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm CORS_ALLOW_ORIGINS production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm OAUTH_USER production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm OAUTH_PASS production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm OAUTH_SECRET_KEY production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm OAUTH_ALGORITHM production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEON_HOST production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEON_DB production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEON_USER production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEON_PASSWORD production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          echo -n "${{ secrets.DEBUG_PROD }}" | vercel env add DEBUG production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.FASTAPI_HOST }}" | vercel env add FASTAPI_HOST production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.FASTAPI_PORT }}" | vercel env add FASTAPI_PORT production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.FASTAPI_TITLE_PROD }}" | vercel env add FASTAPI_TITLE production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.FASTAPI_VERSION }}" | vercel env add FASTAPI_VERSION production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.CORS_ALLOW_ORIGINS }}" | vercel env add CORS_ALLOW_ORIGINS production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.OAUTH_USER }}" | vercel env add OAUTH_USER production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.OAUTH_PASS }}" | vercel env add OAUTH_PASS production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.OAUTH_SECRET_KEY }}" | vercel env add OAUTH_SECRET_KEY production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.OAUTH_ALGORITHM }}" | vercel env add OAUTH_ALGORITHM production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN }}" | vercel env add OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN }}" | vercel env add OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.NEON_HOST }}" | vercel env add NEON_HOST production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.NEON_DB }}" | vercel env add NEON_DB production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.NEON_USER }}" | vercel env add NEON_USER production --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.NEON_PASSWORD }}" | vercel env add NEON_PASSWORD production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Verify Vercel Environment Variables
        run: |
          echo "Listing Vercel environment variables:"
          vercel env ls production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DEBUG: ${{ secrets.DEBUG_PROD }}
          FASTAPI_HOST: ${{ secrets.FASTAPI_HOST }}
          FASTAPI_PORT: ${{ secrets.FASTAPI_PORT }}
          FASTAPI_TITLE: ${{ secrets.FASTAPI_TITLE_PROD }}
          FASTAPI_VERSION: ${{ secrets.FASTAPI_VERSION }}
          CORS_ALLOW_ORIGINS: ${{ secrets.CORS_ALLOW_ORIGINS }}
          OAUTH_USER: ${{ secrets.OAUTH_USER }}
          OAUTH_PASS: ${{ secrets.OAUTH_PASS }}
          OAUTH_SECRET_KEY: ${{ secrets.OAUTH_SECRET_KEY }}
          OAUTH_ALGORITHM: ${{ secrets.OAUTH_ALGORITHM }}
          OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN: ${{ secrets.OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN }}
          OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN: ${{ secrets.OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN }}
          NEON_HOST: ${{ secrets.NEON_HOST }}
          NEON_DB: ${{ secrets.NEON_DB }}
          NEON_USER: ${{ secrets.NEON_USER }}
          NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DEBUG: ${{ secrets.DEBUG_PROD }}
          FASTAPI_HOST: ${{ secrets.FASTAPI_HOST }}
          FASTAPI_PORT: ${{ secrets.FASTAPI_PORT }}
          FASTAPI_TITLE: ${{ secrets.FASTAPI_TITLE_PROD }}
          FASTAPI_VERSION: ${{ secrets.FASTAPI_VERSION }}
          CORS_ALLOW_ORIGINS: ${{ secrets.CORS_ALLOW_ORIGINS }}
          OAUTH_USER: ${{ secrets.OAUTH_USER }}
          OAUTH_PASS: ${{ secrets.OAUTH_PASS }}
          OAUTH_SECRET_KEY: ${{ secrets.OAUTH_SECRET_KEY }}
          OAUTH_ALGORITHM: ${{ secrets.OAUTH_ALGORITHM }}
          OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN: ${{ secrets.OAUTH_EXPIRE_MINUTES_ACCESS_TOKEN }}
          OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN: ${{ secrets.OAUTH_EXPIRE_MINUTES_REFRESH_TOKEN }}
          NEON_HOST: ${{ secrets.NEON_HOST }}
          NEON_DB: ${{ secrets.NEON_DB }}
          NEON_USER: ${{ secrets.NEON_USER }}
          NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
